### ISSUE TITLE
initialize fn can be called multiple times if result is falsey

### ISSUE THREAD

**Issue by derek-rmd** [donavon/use-instance#3]
initialization is called whenever `ref.current` is falsey
this could cause multiple calls to an initialization function

for example if wanting to replace `const value = useMemo(expensiveFn, []);`
I could write `const value = useInstance(expensiveFn);` instead
but I would only ever expect this to run once regardless of the value it returns

```js
test('should only initialize once', () => {
  let count = 0;
  const { result, rerender } = renderHook(() =>
    useInstance(() => {
      count++;
      return false;
    })
  );
  rerender();
  expect(count).toBe(1); // FAILS!
});
```

the approach I used is 

```js
const UNINITIALIZED = Symbol('useInstance_uninitialized');

const useInstance = (initialValOrFn = {}) => {
  const ref = useRef(UNINITIALIZED);
  if (ref.current === UNINITIALIZED) {
    ref.current = typeof initialValOrFn === 'function' ? initialValOrFn() : initialValOrFn;
  }
  return ref.current;
};
```

**Comment by donavon** [comment]
@all-contributors please add @derek-rmd for code

v0.3.0 (now on npm) implements your fix. good catch! thx. sorry so late.
